import type { BusinessRulesDocumentSource } from "./types";

function bulletList(items: string[], emptyLabel: string): string {
  if (items.length === 0) {
    return `- ${emptyLabel}`;
  }
  return items.map((item) => `- ${item}`).join("\n");
}

/**
 * Render BUSINESS_RULES.md markdown from extracted Engineering Model source.
 * Deterministic: same source always produces the same markdown.
 */
export function renderBusinessRulesMarkdown(
  source: BusinessRulesDocumentSource,
  modelFingerprint: string,
): { markdown: string; sections: string[] } {
  const sections = [
    "Document Purpose",
    "Project Context",
    "Business Goals",
    "Business Rules",
    "Rules By Status",
    "Traceability",
    "Related Documents",
    "Generation Metadata",
  ];

  const ruleBlocks =
    source.businessRules.length === 0
      ? "_No business rules recorded in Engineering Model._"
      : source.businessRules
          .map((rule) => {
            const modules =
              rule.relatedModuleIds.length > 0
                ? rule.relatedModuleIds.map((id) => `\`${id}\``).join(", ")
                : "None recorded";
            return `### ${rule.id}

- Description: ${rule.description}
- Status: \`${rule.status}\`
- Source: \`${rule.source}\`
- Related Modules: ${modules}`;
          })
          .join("\n\n");

  const statuses = ["confirmed", "inferred", "draft"] as const;
  const statusBlocks = statuses
    .map((status) => {
      const rules = source.businessRules.filter((rule) => rule.status === status);
      const list =
        rules.length === 0
          ? "- None"
          : rules.map((rule) => `- \`${rule.id}\` — ${rule.description}`).join("\n");
      return `### ${status}

${list}`;
    })
    .join("\n\n");

  const moduleList =
    source.modules.length === 0
      ? "- None recorded in Engineering Model"
      : source.modules
          .map((projectModule) => `- ${projectModule.name} (\`${projectModule.id}\`)`)
          .join("\n");

  const markdown = `# BUSINESS_RULES.md

Version: 1.0.0

Status: Generated

Source Of Truth: Engineering Model

Model Fingerprint: ${modelFingerprint}

Engineering Model Schema Version: ${source.modelSchemaVersion}

---

# Document Purpose

This document defines the business rules and constraints derived from the validated Engineering Model for **${source.projectName || "Unnamed project"}**.

Business rules describe policy and decision constraints. They do not prescribe technical implementation.

---

# Project Context

- Project ID: \`${source.projectId || "unknown"}\`
- Project Name: ${source.projectName || "Unnamed project"}
- Project Type: ${source.projectTypeLabel || source.projectType || "Unspecified"}
- Complexity Level: \`${source.complexityLevel}\`
- Business Goal: ${source.businessGoal || "No business goal recorded in Engineering Model."}

---

# Business Goals

${bulletList(source.businessGoals, "No business goals recorded in Engineering Model.")}

---

# Business Rules

Business rules are derived from Engineering Model business rule candidates.

${ruleBlocks}

---

# Rules By Status

${statusBlocks}

---

# Traceability

## Modules Referenced

${moduleList}

## Rule Counts

- Total Business Rules: ${source.businessRules.length}
- Confirmed: ${source.businessRules.filter((rule) => rule.status === "confirmed").length}
- Inferred: ${source.businessRules.filter((rule) => rule.status === "inferred").length}
- Draft: ${source.businessRules.filter((rule) => rule.status === "draft").length}

---

# Related Documents

- PROJECT.md
- REQUIREMENTS.md
- MODULES.md
- DATABASE.md
- API.md
- TASKS.md
- README.md
- AGENTS.md

---

# Generation Metadata

Generated By

AI Project Architect — Phase 4.2.3 BUSINESS_RULES.md Generator

Generation Date

${source.modelCreatedAt}

Analysis Confidence

${source.analysisConfidence}

Model Warnings

${bulletList(source.warnings, "None")}

Status

Generated from Engineering Model
`;

  return { markdown, sections };
}
