import type { NormalizedDiscovery } from "@/engines/contracts";
import type {
  ComplexityLevel,
  RecommendedTechnologyStack,
} from "../types";

/**
 * Recommends a technology stack.
 * Does not call any AI provider.
 * Does not generate source code or repositories.
 */
export function buildRecommendedTechnologyStack(
  discovery: NormalizedDiscovery,
  complexityLevel: ComplexityLevel,
): RecommendedTechnologyStack {
  const frontend = ["Next.js", "React", "TypeScript", "Tailwind CSS"];
  const backend = ["Next.js App Router server routes", "TypeScript"];
  const database =
    complexityLevel === "tiny" || complexityLevel === "small"
      ? ["PostgreSQL", "Prisma (optional)"]
      : ["PostgreSQL", "Prisma or Drizzle ORM", "Redis (optional cache)"];
  const infrastructure =
    complexityLevel === "tiny"
      ? ["Single-environment hosting", "Environment variables for secrets"]
      : [
          "CI/CD pipeline",
          ...discovery.deployment.environments.map(
            (environment) => `${environment} environment`,
          ),
          "Managed PostgreSQL",
        ];

  const aiServices = [
    "OpenAI Responses API (recommended for future Documentation Engine only)",
  ];

  const notes = [
    "This stack is a recommendation only.",
    "No AI provider is invoked by the Analysis Engine.",
    "No repository or application source code is generated by this engine.",
  ];

  if (discovery.integrations.some((item) => item.id.includes("stripe"))) {
    notes.push("Stripe SDK should be isolated behind a payments adapter.");
  }

  if (discovery.project.type === "clinic") {
    notes.push(
      "Prefer audit-friendly persistence and strict role checks for clinical data paths.",
    );
  }

  return {
    frontend,
    backend,
    database,
    infrastructure,
    aiServices,
    rationale: [
      "Aligned with AI Project Architect platform foundation (Next.js, React, TypeScript, Tailwind).",
      `Complexity level "${complexityLevel}" informs data and infrastructure depth.`,
      `UI platforms from Discovery: ${discovery.ui.platforms.join(", ")}.`,
      `Deployment strategy from Discovery: ${discovery.deployment.strategy}.`,
    ],
    notes,
  };
}
